---
- name: Ensure grafana image is pulled
  docker_image:
    name: "{{ monitoring_grafana_docker_image }}"
    source:  "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ monitoring_grafana_docker_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else monitoring_grafana_docker_image_force_pull }}"

- name: Ensure monitoring-grafana.service installed
  template:
    src: "{{ role_path }}/templates/monitoring-grafana.service.j2"
    dest: "{{ monitoring_systemd_path }}/monitoring-grafana.service"
    mode: 0644
  register: monitoring_grafana_systemd_service_result

- name: Ensure systemd reloaded after monitoring-grafana.service installation
  service:
    daemon_reload: yes
  when: "monitoring_grafana_systemd_service_result.changed|bool"
