---
- name: Check variable types
  assert:
    that:
      - monitoring_grafana_server is mapping
      - monitoring_grafana_database is mapping
      - monitoring_grafana_security is mapping

- name: Fail when datasources aren't configured when dashboards are set to be installed
  fail:
    msg: "You need to specify datasources for dashboards!!!"
  when: monitoring_grafana_dashboards != [] and monitoring_grafana_datasources == []

- name: Fail when grafana admin user isn't set
  fail:
    msg: "Please specify grafana admin user (monitoring_grafana_security.admin_user)"
  when:
    - monitoring_grafana_security.admin_user == '' or
      monitoring_grafana_security.admin_user is not defined

- name: Fail when grafana admin password isn't set
  fail:
    msg: "Please specify grafana admin password (monitoring_grafana_security.admin_password)"
  when:
    - monitoring_grafana_security.admin_password == '' or
      monitoring_grafana_security.admin_password is not defined

- name: Fail on incorrect variable types in datasource definitions
  fail:
    msg: "Boolean variables in monitoring_grafana_datasources shouldn't be passed as strings. Please remove unneeded apostrophes."
  when: ( item.isDefault is defined and item.isDefault is string ) or
        ( item.basicAuth is defined and item.basicAuth is string )
  with_items: "{{ monitoring_grafana_datasources }}"

- name: Fail on bad database configuration
  fail:
    msg: "Wrong database configuration. Please look at http://docs.grafana.org/installation/configuration/#database"
  when: ( monitoring_grafana_database.type == "sqlite3" and monitoring_grafana_database.url is defined ) or
        ( monitoring_grafana_database.type != "sqlite3" and monitoring_grafana_database.path is defined ) or
        ( monitoring_grafana_database.type == "sqlite3" and monitoring_grafana_database.host is defined ) or
        ( monitoring_grafana_database.type == "sqlite3" and monitoring_grafana_database.user is defined ) or
        ( monitoring_grafana_database.type == "sqlite3" and monitoring_grafana_database.password is defined ) or
        ( monitoring_grafana_database.type == "sqlite3" and monitoring_grafana_database.server_cert_name is defined )

- name: Fail when grafana domain isn't properly configured
  fail:
    msg: "Check server configuration. Please look at http://docs.grafana.org/installation/configuration/#server"
  when:
    - monitoring_grafana_server.root_url is defined
    - monitoring_grafana_server.root_url is search(monitoring_grafana_server.domain)

- name: Fail when monitoring_grafana_api_keys uses invalid role names
  fail:
    msg: "Check monitoring_grafana_api_keys. The role can only be one of the following values: Viewer, Editor or Admin."
  when:
    - item.role not in ['Viewer', 'Editor', 'Admin']
  with_items: "{{ monitoring_grafana_api_keys }}"

- name: Fail when grafana_ldap isn't set when grafana_auth.ldap is
  fail:
    msg: "You need to configure monitoring_grafana_ldap.servers and monitoring_grafana_ldap.group_mappings when monitoring_grafana_auth.ldap is set"
  when:
    - "'ldap' in monitoring_grafana_auth"
    - monitoring_grafana_ldap is not defined or ('servers' not in monitoring_grafana_ldap or 'group_mappings' not in monitoring_grafana_ldap)

- name: Force monitoring_grafana_use_provisioning to false if monitoring_grafana_version is < 5.0 ( grafana_version is set to '{{ monitoring_grafana_version }}' )
  set_fact:
    monitoring_grafana_use_provisioning: false
  when:
    - monitoring_grafana_version != 'latest'
    - monitoring_grafana_version is version_compare('5.0', '<')

- name: Fail if grafana_port is lower than 1024 and monitoring_grafana_cap_net_bind_service is not true
  fail:
    msg: Trying to use a port lower than 1024 without setting monitoring_grafana_cap_net_bind_service.
  when:
    - monitoring_grafana_port | int <= 1024
    - not monitoring_grafana_cap_net_bind_service

- name: Fail if monitoring_grafana_server.socket not defined when in socket mode
  fail:
    msg: "You need to configure grafana_server.socket when grafana_server.protocol is set to 'socket'"
  when:
    - monitoring_grafana_server.protocol is defined and monitoring_grafana_server.protocol == 'socket'
    - monitoring_grafana_server.socket is undefined or monitoring_grafana_server.socket == ''

- name: Ensure grafana user exists
  user:
    name: "{{ monitoring_grafana_user_username }}"
    group: "{{ monitoring_grafana_user_groupname }}"