---
- name: restart grafana
  become: true
  service:
    name: monitoring-grafana
    state: restarted
  tags:
    - grafana_run

- name: Set privileges on provisioned dashboards
  become: true
  file:
    path: "{{ monitoring_grafana_data_path }}/dashboards"
    recurse: true
    owner: "{{ monitoring_grafana_user_username }}"
    group: "{{ monitoring_grafana_user_groupname }}"
    mode: 0640
  listen: "provisioned dashboards changed"

- name: Set privileges on provisioned dashboards directory
  become: true
  file:
    path: "{{ monitoring_grafana_data_path }}/dashboards"
    state: directory
    recurse: false
    mode: 0755
  listen: "provisioned dashboards changed"
